#! /bin/sh

pgrep +x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh --hack
#$HOME/.config/polybar/cuts/preview.sh &
#polybar -q mid -c /home/zereft/.config/polybar/forest/preview.sh &

nitrogen --restore &
picom --experimental-backends &

#_____________________config de los monitores_____________________#

bspc monitor -d  一  二  三  四  五  六  七  八  九 
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 0000 0001 0010 0011 0100 0101 0111 1000 1100
#bspc monitor -d 1 2 3 4 5 6 7 8 9

#______________________

bspc config border_width         1
bspc config window_gap          10
#____________config _____________________
bspc config normal_border_color "$color8"
bspc config active_border_color "$color7"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color0"

SPACES=$(bspc query -D)
for SPACE in $SPACES
do
  bspc config -d ${SPACE} window_gap      10
  bspc config -d ${SPACE} top_padding     25
  bspc config -d ${SPACE} bottom_padding  25
  bspc config -d ${SPACE} left_padding   30
  bspc config -d ${SPACE} right_padding  30
done

#bspc config automatic_scheme      spiral
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true
bspc config focus_follows_pointer true

#bspc desktop ^1 -l monocle
#bspc desktop ^2 -l monocle
#bspc desktop ^5 -l monocle
#bspc desktop ^6 -l monocle
#bspc desktop ^9 -l monocle
#bspc desktop ^10 -l monocle

#_______finl_________________

bspc rule -a Gimp desktop='V' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#_____reglas_______
bspc rule -a xfce4-terminal:Tiled desktop='^1' follow=on
bspc rule -a xfce4-terminal:Tmux desktop='^1' follow=on
bspc rule -a Subl3 desktop='^3'
bspc rule -a mpv state=floating sticky=on rectangle=300x180+1060+475
bscp rule -a polybar manage=off
FLOATING_DESKTOP_ID=$(bspc query -D -d '^7')
bspc subscribe node_manage | while read -a msg ; do
	desk_id=${msg[2]}
	wid=${msg[3]}
	[ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
